=== camenduru/flux.1-dev-upscaler-tost/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "Flux.1 Dev ControlNet Upscaler",
      "author": "Jasper AI, Forest Labs",
      "code": "https://github.com/black-forest-labs/flux",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/flux.1-dev-upscaler.ipynb",
      "tags": [
        "Image to Image"
      ],
      "widget": "readme"
    },
    "upload": {
      "type": "string",
      "widget": "upload",
      "upload_url": "https://litterbox.catbox.moe/resources/internals/api.php",
      "property": "input_image_check"
    },
    "input_image_check": {
      "type": "string",
      "description": "Input Image URL",
      "widget": "textarea"
    },
    "positive_prompt": {
      "type": "string",
      "description": "Prompt",
      "widget": "textarea"
    },
    "seed": {
      "type": "integer",
      "description": "Seed (if 0 random)"
    },
    "upscale_method": {
      "type": "string",
      "widget": "select",
      "description": "Upscale Method",
      "oneOf": [
        {
          "description": "lanczos",
          "enum": [
            "lanczos"
          ]
        }
      ],
      "default": "lanczos"
    },
    "scale_by": {
      "type": "integer",
      "widget": "select",
      "description": "Scale By",
      "oneOf": [
        {
          "description": "1",
          "enum": [
            1
          ]
        },
        {
          "description": "2",
          "enum": [
            2
          ]
        },
        {
          "description": "3",
          "enum": [
            3
          ]
        },
        {
          "description": "4",
          "enum": [
            4
          ]
        },
        {
          "description": "5",
          "enum": [
            5
          ]
        }
      ],
      "default": 5
    },
    "strength": {
        "type": "number",
        "description": "ControlNet Strength",
        "minimum": 0.5,
        "maximum": 1.0,
        "widget": "select",
        "oneOf": [
          {
            "description": "0.5",
            "enum": [
              0.5
            ]
          },
          {
            "description": "0.55",
            "enum": [
              0.55
            ]
          },
          {
            "description": "0.6",
            "enum": [
              0.6
            ]
          },
          {
            "description": "0.65",
            "enum": [
              0.65
            ]
          },
          {
            "description": "0.7",
            "enum": [
              0.7
            ]
          },
          {
            "description": "0.75",
            "enum": [
              0.75
            ]
          },
          {
            "description": "0.8",
            "enum": [
              0.8
            ]
          },
          {
            "description": "0.85",
            "enum": [
              0.85
            ]
          },
          {
            "description": "0.9",
            "enum": [
              0.9
            ]
          },
          {
            "description": "0.95",
            "enum": [
              0.95
            ]
          },
          {
            "description": "1.0",
            "enum": [
              1.0
            ]
          }
        ],
        "default": 0.65
    },
    "steps": {
      "type": "integer",
      "widget": "select",
      "description": "Steps",
      "oneOf": [
        {
          "description": "10",
          "enum": [
            10
          ]
        },
        {
          "description": "15",
          "enum": [
            15
          ]
        },
        {
          "description": "20",
          "enum": [
            20
          ]
        },
        {
          "description": "25",
          "enum": [
            25
          ]
        },
        {
          "description": "30",
          "enum": [
            30
          ]
        }
      ],
      "default": 20
    },
    "cfg": {
      "type": "number",
      "description": "CFG",
      "widget": "hidden"
    },
    "guidance": {
      "type": "number",
      "description": "Guidance"
    },
    "sampler_name": {
      "type": "string",
      "widget": "select",
      "description": "Sampler Name",
      "oneOf": [
        {
          "description": "euler",
          "enum": [
            "euler"
          ]
        },
        {
          "description": "heun",
          "enum": [
            "heun"
          ]
        },
        {
          "description": "heunpp2",
          "enum": [
            "heunpp2"
          ]
        },
        {
          "description": "dpm_2",
          "enum": [
            "dpm_2"
          ]
        },
        {
          "description": "lms",
          "enum": [
            "lms"
          ]
        },
        {
          "description": "dpmpp_2m",
          "enum": [
            "dpmpp_2m"
          ]
        },
        {
          "description": "ipndm",
          "enum": [
            "ipndm"
          ]
        },
        {
          "description": "deis",
          "enum": [
            "deis"
          ]
        },
        {
          "description": "ddim",
          "enum": [
            "ddim"
          ]
        },
        {
          "description": "uni_pc",
          "enum": [
            "uni_pc"
          ]
        },
        {
          "description": "uni_pc_bh2",
          "enum": [
            "uni_pc_bh2"
          ]
        }
      ],
      "default": "euler"
    },
    "scheduler": {
      "type": "string",
      "widget": "select",
      "description": "Scheduler",
      "oneOf": [
        {
          "description": "beta",
          "enum": [
            "beta"
          ]
        },
        {
          "description": "normal",
          "enum": [
            "normal"
          ]
        },
        {
          "description": "sgm_uniform",
          "enum": [
            "sgm_uniform"
          ]
        },
        {
          "description": "simple",
          "enum": [
            "simple"
          ]
        },
        {
          "description": "ddim_uniform",
          "enum": [
            "ddim_uniform"
          ]
        }
      ],
      "default": "simple"
    },
    "example": {
      "type": "string",
      "image1": "https://fakeimg.pl/320x192/282828/eae0d0/?text=input#.png",
      "image2": "https://files.catbox.moe/m2vlnx.jpg",
      "image3": "https://fakeimg.pl/320x192/282828/eae0d0/?text=output#.png",
      "image4": "https://files.catbox.moe/7bxusa.png",
      "widget": "example"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/flux.1-dev-upscaler-tost/model.json
{
    "input_image_check": "https://files.catbox.moe/m2vlnx.jpg",
    "positive_prompt": "professional raw photo",
    "seed": 0,
    "upscale_method": "lanczos",
    "scale_by": 5,
    "strength": 0.65,
    "steps": 25,
    "cfg": 1,
    "guidance": 3.5,
    "sampler_name": "euler",
    "scheduler": "normal"
}
